name: Deploy to AWS Lambda

on:
  push:
    branches:
    - mongodb

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          ls
          pwd
          
