name: Deploy to AWS Lambda

on:
  push:
    branches:
    - mongodb

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mv Config.example.py Config.py
          echo ${{ secrets.MONGODB_CERTIFICATE }} > ${{ secrets.MONGODB_CERTIFICATE_NAME }}
      - name: Testing
        run: |
          ls -la
